### ISSUE TITLE
Append to existing text file - in >3.0

### ISSUE THREAD

**Issue by bobbyrne01** [bobbyrne01/save-text-to-file-firefox#90] opened 2017-12-27 00:47 UTC
fyi @quarto505

**Comment by sten9844** [comment] 2018-01-09 16:43
Is this currently implemented? SttF 3.0.1 and FF 57.0.3 x64

**Comment by Dboingue** [comment] 2020-05-21 02:31
Duplicate of #
https://github.com/bobbyrne01/save-text-to-file-firefox/issues/95#issue-310103527

**Comment by bobbyrne01** [comment] 2020-08-20 09:08
@quarto505 @sten9844 This is now available again in latest release (4.1.0). Users can save (append) text to an existing file.

Please retest using latest install instructions here:

https://github.com/bobbyrne01/save-text-to-file-firefox#save-text-to-file-firefox

**Closed** 2020-08-20 09:08 UTC
Labels: enhancement
