### ISSUE TITLE
Firefox Quantum

### ISSUE THREAD

**Issue by chris1691** [bobbyrne01/save-text-to-file-firefox#87] opened 2017-11-17 07:55 UTC
Please let us know whether an update is planned to stay compatible with Firefox Quantum. Thank you.

**Comment by yoyoma2** [comment] 2017-11-22 04:18
This is a duplicate of issue #85.  See issue #85 for a workaround using a different extension.

**Comment by bobbyrne01** [comment] 2017-12-24 15:34
Try version 3.0:

https://addons.mozilla.org/en-US/firefox/addon/save-text-to-file/versions/?page=1#version-3.0

**Closed by bobbyrne01** 2017-12-24 15:34 UTC
