### ISSUE TITLE
Save text to the same text file

### ISSUE THREAD

**Issue by hollysheep** [bobbyrne01/save-text-to-file-firefox#95] opened 2018-03-30 16:06 UTC
Hi,

is it possible to add the text to an existing text file? every text should saved in a new line in the same text file.

**Comment by thaihbn** [comment] 2018-04-13 05:50
Rollback to Firefox 56 and install the old version of Save text to file. So far, this is the only way we can save text to the same text file. 

The new version of Save text to file remove "Append to existing file" in save mode. I hope the developer would bring this function back. 

Anyway, i would stop using Firefox. It's time to quit Firefox now.

**Comment by Dboingue** [comment] 2020-05-21 02:30
Duplicate of #
https://github.com/bobbyrne01/save-text-to-file-firefox/issues/90#issue-284627507

**Comment by bobbyrne01** [comment] 2020-08-20 09:14
@hollysheep @thaihbn @Dboingue This is now available again in latest release (4.1.0). Users can save (append) text to an existing file.

Please retest using latest install instructions here:

https://github.com/bobbyrne01/save-text-to-file-firefox#save-text-to-file-firefox

Or if you prefer Chrome, use:

https://github.com/bobbyrne01/save-text-to-file-chrome#save-text-to-file-chrome

**Closed** 2020-08-20 09:14 UTC
Labels: enhancement
